##################
# Package metadata. Unless you are forking, this shouldn't change.
# These are used to fill templated variables inside files (eg: {PUKE-FOO-BAR})
# and in some cases to construct build / deploy paths
##################
baseYank:
  package:
    # Code name (eg: {PUKE-PACKAGE-NAME})
      name: lxxl.js
    # Version  (eg: {PUKE-PACKAGE-VERSION})
      version: '0.2'
  rights:
    # License link (eg: {PUKE-RIGHTS-LICENSE})
      license: '<a href="http://www.gnu.org/licenses/agpl-3.0.html">Afero GPL</a>'
    # Copyright to be replaced in files (eg: {PUKE-RIGHTS-COPYRIGHT})
      copyright: 'All rights reserved <a href="http://education-numerique.com">E&N</a>'
    # Author (eg: {PUKE-RIGHTS-AUTHOR})
      author: '<a href="mailto:dev@webitup.fr">Mangled Deutz & Raildecom</a>'
  git:
    # Repository base url (eg: {PUKE-GIT-ROOT})
      root: 'https://raw.github.com/Education-Numerique/authoring.js/master/src/'




##################
# Platform dependent stuff
# These specify build- / run- time paths.
# You should override them either by adding a config-USERNAME-UNAME node in this file
# or by creating a config-USERNAME-UNAME.json file and adding a "userYank" node in it.
##################
defaultYank:
  # Base root path against which relative paths may be resolved
  # ROOT: '${HOME}/buildd'
  root: './'

  # Specific paths - if using a relative path, will be resolved against "root"
  # You may mix env variables as well (${HOME}) - see puke documentation for more
  paths:
      build: 'tmp'
      deploy: 'lib'
      doc: 'doc'

  links:
    airstrip:
      version: '1.0'
      url: 'https://static.sn.ackitup.net/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/lib/webitup/spitfire.json'
    jsboot:
        version: '0.2'
        url: 'https://static.sn.ackitup.net/lib/webitup/jsboot.json'

  settings:
      # Instruct puke to copy trunk versions of the shims - only of use for me:
      # VARIANT: "bleed"
      variant: "bleednot"

  ACCESS:
      LXXL:
          KEY: 'XXX'
          SECRET: 'XXXXXXX'
      FACEBOOK:
          # KEY: '182703758509672'
          KEY: 'XXXXXX'
          # SECRET: 'fe4d6a584dfc7bfad6b3b385b19a7c7e'
      GA: 'UA-XXXXX'

  DEBUG: 'true'
  MINIFY: 'true'



# Integration
config-jenkins-linux:
  paths:
    deploy: '/var/www/deploy/static/clients/lxxl'
  links:
    airstrip:
      version: '1.0'
      url: 'https://static.sn.ackitup.net/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/lib/webitup/spitfire.json'
    jsboot:
        version: '0.2'
        url: 'https://static.sn.ackitup.net/lib/webitup/jsboot.json'
    self:
      url: '//app.sn.ackitup.net/'

  service:
    port: ''
    # host: 'app.lxxl.com'
    host: 'api.education-et-numerique.fr'


  ACCESS:
      LXXL:
          KEY: 'XXX'
          SECRET: 'XXXXXXX'
      FACEBOOK:
          # KEY: '182703758509672'
          KEY: 'XXXXXX'
          # SECRET: 'fe4d6a584dfc7bfad6b3b385b19a7c7e'
      GA: 'UA-XXXXX'

  DEBUG: 'true'
  MINIFY: 'true'



config-raildecom-darwin:
  root: '${HOME}/workspace/webitup/buildd'
  paths:
    deploy: '${HOME}/workspace/webitup/deploy/web/static/lib/lxxl'
  # DOC_ROOT: '/var/www/deploy/static/doc/spitfire'
  links:
    airstrip:
      version: '1.0'
      url: 'https://static.sn.ackitup.net/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/lib/webitup/spitfire.json'
    jsboot:
        version: '0.2'
        url: 'https://static.sn.ackitup.net/lib/webitup/jsboot.json'
    self:
      url: '//dev.app.sn.ackitup.net/'

  service:
    port: '8081'
    host: 'localhost'


  ACCESS:
      LXXL:
          KEY: 'XXX'
          SECRET: 'XXXXXXX'
      FACEBOOK:
          # KEY: '182703758509672'
          KEY: 'XXXXXX'
          # SECRET: 'fe4d6a584dfc7bfad6b3b385b19a7c7e'
      GA: 'UA-XXXXX'

  DEBUG: 'true'
  MINIFY: 'false'




config-dmp-darwin:
  root: "${HOME}/buildd/stage.webitup.org"
  paths:
    deploy: "${HOME}/buildd/deploy.webitup.org/web/app/lxxl"

  links:
      airstrip:
        version: '1.0'
        url: 'http://static.loft.sn.ackitup.net:4242/airstrip.json'
      spitfire:
          version: '1.0'
          url: 'http://static.loft.sn.ackitup.net:4242/lib/webitup/spitfire.json'
      jsboot:
          version: '0.2'
          url: 'http://static.loft.sn.ackitup.net:4242/lib/webitup/jsboot.json'
      self:
        url: '//app.loft.sn.ackitup.net:4242/'

  service:
    port: '90'
    # host: 'app.lxxl.com'
    host: 'api.education-et-numerique.fr'

  ACCESS:
      LXXL:
          KEY: 'XXX'
          SECRET: 'XXXXXXX'
      FACEBOOK:
          # KEY: '182703758509672'
          KEY: 'XXXXXX'
          # SECRET: 'fe4d6a584dfc7bfad6b3b385b19a7c7e'
      GA: 'UA-XXXXX'

  DEBUG: 'true'
  MINIFY: 'false'





config-JB-darwin:
  root: "${HOME}/tmp-lxxl"
  paths:
    deploy: "${HOME}/Sites/lxxl"

  links:
      airstrip:
        version: '1.0'
        url: 'http://static.loft.sn.ackitup.net:4242/airstrip.json'
      spitfire:
          version: '1.0'
          url: 'http://static.loft.sn.ackitup.net:4242/lib/webitup/spitfire.json'
      jsboot:
          version: '0.2'
          url: 'https://static.sn.ackitup.net/lib/webitup/jsboot.json'
      self:
        url: '//app.loft.sn.ackitup.net:4242/'


  ACCESS:
      LXXL:
          KEY: 'XXX'
          SECRET: 'XXXXXXX'
      FACEBOOK:
          # KEY: '182703758509672'
          KEY: 'XXXXXX'
          # SECRET: 'fe4d6a584dfc7bfad6b3b385b19a7c7e'
      GA: 'UA-XXXXX'

  DEBUG: 'true'
  MINIFY: 'false'


